// <auto-generated />
using System;
using EfProject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfProject.Migrations
{
    [DbContext(typeof(TareasContext))]
    partial class TareasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EfProject.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("536e8e50-70af-4f44-a9fa-3defcc6d174a"),
                            Descripcion = "Actividades Pendientes de tarabajo",
                            Nombre = "Actividades Pendientes",
                            Peso = 30
                        },
                        new
                        {
                            CategoriaId = new Guid("7198ea7b-115b-416b-952d-1f47bfbc0208"),
                            Descripcion = "Actividades pendeintes personales",
                            Nombre = "Actividades Personales",
                            Peso = 50
                        });
                });

            modelBuilder.Entity("EfProject.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<int>("Prioridad")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("696473d8-38d9-47d4-9498-3a66d3717d55"),
                            CategoriaId = new Guid("536e8e50-70af-4f44-a9fa-3defcc6d174a"),
                            Descripcion = "Terminar actualizacion masiva ECOTIC",
                            FechaCreacion = new DateTime(2023, 8, 25, 10, 48, 24, 918, DateTimeKind.Local).AddTicks(7805),
                            FechaEntrega = new DateTime(2023, 8, 25, 10, 48, 24, 918, DateTimeKind.Local).AddTicks(7817),
                            Prioridad = 1,
                            Titulo = "Programacion"
                        },
                        new
                        {
                            TareaId = new Guid("ec4ae34e-7c21-4a42-8832-b3bbbe8ebf6b"),
                            CategoriaId = new Guid("7198ea7b-115b-416b-952d-1f47bfbc0208"),
                            Descripcion = "Hacer Ejercicio 3 veces a la semana",
                            FechaCreacion = new DateTime(2023, 8, 25, 10, 48, 24, 918, DateTimeKind.Local).AddTicks(7822),
                            FechaEntrega = new DateTime(2023, 8, 25, 10, 48, 24, 918, DateTimeKind.Local).AddTicks(7822),
                            Prioridad = 1,
                            Titulo = "Ejercicio"
                        });
                });

            modelBuilder.Entity("EfProject.Models.Tarea", b =>
                {
                    b.HasOne("EfProject.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("EfProject.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
